### ISSUE TITLE
malloc(): memory corruption

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [ku-cbd/PhageBoost#13]
Hi Kimmo
I'm Trying to launch PhageBoost command line on 1 of my dataset, and I get this super long error. It looks like a cython issue? 
Install wise I followed the Pypi instructions.
Here is the command line I launched:
`PhageBoost -j 50 -f contigs/contig.fa -meta 1 --mincontigsize 500 -o phageboost `

Any idea ? 

```                                              
processing: contigs
*** Error in `/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python': malloc(): memory corruption: 0x0000558b4873cd60 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7f586f20e7f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8215e)[0x7f586f21915e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f586f21b1d4]
/lib/x86_64-linux-gnu/libc.so.6(qsort_r+0x79)[0x7f586f1d0359]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/pyrodigal/_pyrodigal.cpython-37m-x86_64-linux-gnu.so(+0xf017)[0x7f586c0c1017]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/pyrodigal/_pyrodigal.cpython-37m-x86_64-linux-gnu.so(+0x155e0)[0x7f586c0c75e0]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyMethodDef_RawFastCallKeywords+0x8d)[0x558ab348272d]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyMethodDescr_FastCallKeywords+0x4f)[0x558ab34897af]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalFrameDefault+0x4bdc)[0x558ab34eec7c]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalCodeWithName+0xc30)[0x558ab3432160]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyFunction_FastCallKeywords+0x387)[0x558ab3482107]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalFrameDefault+0x4a89)[0x558ab34eeb29]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x558ab3481e7b]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalFrameDefault+0x416)[0x558ab34ea4b6]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x558ab3481e7b]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalFrameDefault+0x416)[0x558ab34ea4b6]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x558ab3431829]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(PyEval_EvalCodeEx+0x44)[0x558ab3432714]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(PyEval_EvalCode+0x1c)[0x558ab343273c]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(+0x22cf14)[0x558ab3549f14]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(PyRun_FileExFlags+0xa1)[0x558ab3554331]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(PyRun_SimpleFileExFlags+0x1c3)[0x558ab3554523]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(+0x238655)[0x558ab3555655]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(_Py_UnixMain+0x3c)[0x558ab355577c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f586f1b7840]
/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/python(+0x1dcff0)[0x558ab34f9ff0]
======= Memory map: ========
558ab331d000-558ab3378000 r--p 00000000 00:2c 507964191                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/bin/python3.7
558ab3378000-558ab3556000 r-xp 0005b000 00:2c 507964191                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/bin/python3.7
558ab3556000-558ab35fe000 r--p 00239000 00:2c 507964191                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/bin/python3.7
558ab35fe000-558ab3601000 r--p 002e0000 00:2c 507964191                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/bin/python3.7
558ab3601000-558ab366a000 rw-p 002e3000 00:2c 507964191                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/bin/python3.7                                                        [57/207]
558ab366a000-558ab368a000 rw-p 00000000 00:00 0 
558ab4914000-558b4d4c3000 rw-p 00000000 00:00 0                          [heap]
7f56ffe7d000-7f56ffebd000 rw-p 00000000 00:00 0 
7f56ffebd000-7f56ffebe000 r--p 00000000 00:2c 505863961                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so
7f56ffebe000-7f56ffec0000 r-xp 00001000 00:2c 505863961                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so
7f56ffec0000-7f56ffec1000 r--p 00003000 00:2c 505863961                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so
7f56ffec1000-7f56ffec2000 r--p 00003000 00:2c 505863961                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so
7f56ffec2000-7f56ffec3000 rw-p 00004000 00:2c 505863961                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so
7f56ffec3000-7f56fff03000 rw-p 00000000 00:00 0 
7f56fff03000-7f56fff0d000 r--p 00000000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff0d000-7f56fff24000 r-xp 0000a000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff24000-7f56fff2d000 r--p 00021000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff2d000-7f56fff2e000 ---p 0002a000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff2e000-7f56fff2f000 r--p 0002a000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff2f000-7f56fff30000 rw-p 0002b000 00:2c 349178407                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libgomp.so.1.0.0
7f56fff30000-7f5718aab000 r-xp 00000000 00:2c 513216733                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/xgboost/lib/libxgboost.so
7f5718aab000-7f5718cab000 ---p 18b7b000 00:2c 513216733                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/xgboost/lib/libxgboost.so
7f5718cab000-7f5718cbe000 rw-p 18b7b000 00:2c 513216733                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/xgboost/lib/libxgboost.so
7f5718cbe000-7f5718d08000 rw-p 00000000 00:00 0 
7f5718d08000-7f5718d0a000 r--p 00000000 00:2c 505863960                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
7f5718d0a000-7f5718d0b000 r-xp 00002000 00:2c 505863960                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
7f5718d0b000-7f5718d0c000 r--p 00003000 00:2c 505863960                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
7f5718d0c000-7f5718d0d000 r--p 00003000 00:2c 505863960                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
7f5718d0d000-7f5718d0e000 rw-p 00004000 00:2c 505863960                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
7f5718d0e000-7f5718d8e000 rw-p 00000000 00:00 0 
7f5718d8e000-7f5718d92000 r--p 00000000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718d92000-7f5718d9a000 r-xp 00004000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718d9a000-7f5718d9d000 r--p 0000c000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718d9d000-7f5718d9e000 ---p 0000f000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718d9e000-7f5718d9f000 r--p 0000f000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718d9f000-7f5718da1000 rw-p 00010000 00:2c 505863995                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so
7f5718da1000-7f5718e61000 rw-p 00000000 00:00 0 
7f5718e61000-7f5718e80000 r--p 00000000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718e80000-7f5718eca000 r-xp 0001f000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718eca000-7f5718ee3000 r--p 00069000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718ee3000-7f5718ee4000 ---p 00082000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718ee4000-7f5718eed000 r--p 00082000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718eed000-7f5718ef1000 rw-p 0008b000 00:2c 382020803                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libssl.so.1.1
7f5718ef1000-7f5718efb000 r--p 00000000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718efb000-7f5718f06000 r-xp 0000a000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718f06000-7f5718f0c000 r--p 00015000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718f0c000-7f5718f0d000 ---p 0001b000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718f0d000-7f5718f0e000 r--p 0001b000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718f0e000-7f5718f13000 rw-p 0001c000 00:2c 505864002                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
7f5718f13000-7f5719153000 rw-p 00000000 00:00 0 
7f5719153000-7f5719170000 r-xp 00000000 00:2c 513216998                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/Bio/Align/_aligners.cpython-37m-x86_64-linux-gnu.
so
7f5719170000-7f5719370000 ---p 0001d000 00:2c 513216998                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/Bio/Align/_aligners.cpython-37m-x86_64-linux-gnu.
so
7f5719370000-7f5719372000 rw-p 0001d000 00:2c 513216998                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/Bio/Align/_aligners.cpython-37m-x86_64-linux-gnu.
so
7f5719372000-7f57193b2000 rw-p 00000000 00:00 0 
7f57193b2000-7f57193c2000 r--p 00000000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f57193c2000-7f571949e000 r-xp 00010000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f571949e000-7f57194cf000 r--p 000ec000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f57194cf000-7f57194d0000 ---p 0011d000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f57194d0000-7f57194d4000 r--p 0011d000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f57194d4000-7f57194d7000 rw-p 00121000 00:2c 345502131                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/libsqlite3.so.0.8.6
7f57194d7000-7f57194df000 r--p 00000000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194df000-7f57194e9000 r-xp 00008000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194e9000-7f57194ed000 r--p 00012000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194ed000-7f57194ee000 ---p 00016000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194ee000-7f57194ef000 r--p 00016000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194ef000-7f57194f1000 rw-p 00017000 00:2c 505863999                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so
7f57194f1000-7f5719531000 rw-p 00000000 00:00 0 
7f5719531000-7f5719544000 r-xp 00000000 00:2c 512166409                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/mvn.cpython-37m-x86_64-linux-gnu.so
7f5719544000-7f5719743000 ---p 00013000 00:2c 512166409                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/mvn.cpython-37m-x86_64-linux-gnu.so
7f5719743000-7f5719745000 rw-p 00012000 00:2c 512166409                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/mvn.cpython-37m-x86_64-linux-gnu.so
7f5719745000-7f571983c000 rw-p 00000000 00:00 0 
7f571983c000-7f571983e000 rw-p 00015000 00:2c 512166409                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/mvn.cpython-37m-x86_64-linux-gnu.so
7f571983e000-7f571987e000 rw-p 00000000 00:00 0 
7f571987e000-7f5719888000 r-xp 00000000 00:2c 512166403                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/statlib.cpython-37m-x86_64-linux-gnu.
so
7f5719888000-7f5719a87000 ---p 0000a000 00:2c 512166403                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/statlib.cpython-37m-x86_64-linux-gnu.
so
7f5719a87000-7f5719a89000 rw-p 00009000 00:2c 512166403                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/statlib.cpython-37m-x86_64-linux-gnu.
so
7f5719a89000-7f5719a8b000 rw-p 0000c000 00:2c 512166403                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/statlib.cpython-37m-x86_64-linux-gnu.
so
7f5719a8b000-7f5719c4b000 rw-p 00000000 00:00 0 
7f5719c4b000-7f5719e86000 r-xp 00000000 00:2c 512165976                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/special/cython_special.cpython-37m-x86_64-l
inux-gnu.so
7f5719e86000-7f571a085000 ---p 0023b000 00:2c 512165976                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/special/cython_special.cpython-37m-x86_64-l
inux-gnu.so
7f571a085000-7f571a097000 rw-p 0023a000 00:2c 512165976                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/special/cython_special.cpython-37m-x86_64-l
inux-gnu.so
7f571a097000-7f571a099000 rw-p 00000000 00:00 0 
7f571a099000-7f571a09f000 rw-p 0024c000 00:2c 512165976                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/special/cython_special.cpython-37m-x86_64-l
inux-gnu.so
7f571a09f000-7f571a11a000 r-xp 00000000 00:2c 512166401                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/_stats.cpython-37m-x86_64-linux-gnu.s
o
7f571a11a000-7f571a319000 ---p 0007b000 00:2c 512166401                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/_stats.cpython-37m-x86_64-linux-gnu.s
o
7f571a319000-7f571a320000 rw-p 0007a000 00:2c 512166401                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/stats/_stats.cpython-37m-x86_64-linux-gnu.s
o
7f571a320000-7f571a322000 rw-p 00000000 00:00 0 
7f571a322000-7f571a36f000 r-xp 00000000 00:2c 512166532                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/interpnd.cpython-37m-x86_64-lin
ux-gnu.so
7f571a36f000-7f571a56e000 ---p 0004d000 00:2c 512166532                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/interpnd.cpython-37m-x86_64-lin
ux-gnu.so
7f571a56e000-7f571a574000 rw-p 0004c000 00:2c 512166532                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/interpnd.cpython-37m-x86_64-lin
ux-gnu.so
7f571a574000-7f571a575000 rw-p 00000000 00:00 0 
7f571a575000-7f571a5be000 r-xp 00000000 00:2c 512166536                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/_ppoly.cpython-37m-x86_64-linux
-gnu.so
7f571a5be000-7f571a7bd000 ---p 00049000 00:2c 512166536                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/_ppoly.cpython-37m-x86_64-linux
-gnu.so
7f571a7bd000-7f571a7c3000 rw-p 00048000 00:2c 512166536                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/_ppoly.cpython-37m-x86_64-linux
-gnu.so
7f571a7c3000-7f571a804000 rw-p 00000000 00:00 0 
7f571a804000-7f571a83c000 r-xp 00000000 00:2c 512166537                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/_bspl.cpython-37m-x86_64-linux-
gnu.so
7f571a83c000-7f571aa3c000 ---p 00038000 00:2c 512166537                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/scipy/interpolate/_bspl.cpython-37m-x86_64-linux-
gnu.so
7f571aa3c000-7f571aa42000 rw-p 00038000 00:2c 512166537                  /mnt/gpfs/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/si
```

**Comment by kkpsiren** [comment]
Hi Seb, it looks like a gene calling error from the pyrodigal https://github.com/althonos/pyrodigal. Can you send me the fasta-file and I'll have a look? Also, can you try without the ```-meta 1``` flag?  Additionally, PhageBoost currently uses single thread so ```-j``` will do you no good :)

**Comment by Sebastien-Raguideau** [comment]
Hi Kimmo,

Thanks for the super fast answer.

Since then I tried to launch per sequence and it worked a lot better. No malloc issue. 

BUT, I do get some cryptic error messages on some of the contigs. I looked into it and this seems to happens only when contigs length is quite small ~ 600 nuc. You may want to catch that. 
```
processing: contig_12488
time after genecalls: 0.20870280265808105
Traceback (most recent call last):
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/bin/PhageBoost", line 8, in <module>
    sys.exit(main())
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/main.py", line 205, in main
    df = calculate_features(genecalls)
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/main.py", line 59, in calculate_features
    df, _, _ = calc_features.df2AAandDNAfeatures(genecalls, name='header')
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/calc_features.py", line 215, in df2AAandDNAfeatures
    DF, DF_AA, DF_DNA = RunAAandDNA(dna_entries, aa_entries, locations)
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/calc_features.py", line 201, in RunAAandDNA
    DF_DNA = RunDNA(DNA_entries, locations, verbose = verbose)
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/calc_features.py", line 189, in RunDNA
    df_CAI = calculate_CAI(entries)
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/calc_features.py", line 73, in calculate_CAI
    CAI.generate_index(sequences)    
  File "/home/sebr/seb/Applications/miniconda3/envs/phageboost/lib/python3.7/site-packages/Bio/SeqUtils/CodonUsage.py", line 121, in generate_index
    rcsu.append(self.codon_count[codon] / denominator)
ZeroDivisionError: float division by zero

```
Here is the corresponding file : [contig_12488.fa](https://github.com/ku-cbd/PhageBoost/files/5516883/contig_12488.txt)


In the mean time if you want to have a look at that malloc issue, I'll send you a dl link to the assembly in a min.
Thanks for help, and your soft :)
