### ISSUE TITLE
AttributeError: symbol not found

### ISSUE THREAD

**Issue by tomdstanton** [ku-cbd/PhageBoost#19]
Hello :)

I am running into some trouble with PhageBoost on my Mac (M1 chip, macOS Monterey).
I installed via pip into a conda environment as recommended by the README and, following a known error, also followed the concluding advice of #17 (https://github.com/ku-cbd/PhageBoost/issues/17#issuecomment-986606238) whereby XGBoost was downgraded to 1.0.2 via conda.
However, during testing, I'm still running into this error below, which looks like it occurs when reading in models?

`
(PhageBoost-env) tom@Toms-MBP data % PhageBoost -f assemblies/*.fasta -o PB -j 4
processing: AJ011_S11_L001
time after genecalls: 96.16339182853699
time after feature calculations: 131.9071910381317
Traceback (most recent call last):
  File "/opt/miniconda3/envs/PhageBoost-env/bin/PhageBoost", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/PhageBoost/main.py", line 223, in main
    model, feats, feats_, limit = read_model_from_file(model_file)
  File "/opt/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/PhageBoost/main.py", line 65, in read_model_from_file
    feats = model.feature_names
  File "/Users/tom/.local/lib/python3.7/site-packages/xgboost/core.py", line 1615, in feature_names
    return self._get_feature_info("feature_name")
  File "/Users/tom/.local/lib/python3.7/site-packages/xgboost/core.py", line 1594, in _get_feature_info
    _LIB.XGBoosterGetStrFeatureInfo(
  File "/opt/miniconda3/envs/PhageBoost-env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/opt/miniconda3/envs/PhageBoost-env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x217a16000, XGBoosterGetStrFeatureInfo): symbol not found
`
Any advice to solve this issue would be greatly appreciated.
I've attached the environment YAML just in case.

Cheers,
Tom
[PhageBoost-env.txt](https://github.com/ku-cbd/PhageBoost/files/7788619/PhageBoost-env.txt)

**Comment by Shawniel** [comment]
I met the same problem, have you solved that?
