### ISSUE TITLE
AttributeError: module 'pyrodigal' has no attribute 'Pyrodigal'

### ISSUE THREAD

**Issue by btemperton** [ku-cbd/PhageBoost#23]
Following the installation instructions:

```
conda create -y -n PhageBoost-env python=3.7 
conda activate PhageBoost-env
pip install PhageBoost 
```
Seems to successfully install. However, when trying to run a test on a set of Coxiella genomes, I am getting the following error:

```
Traceback (most recent call last):
  File "/home/artic/miniconda3/envs/PhageBoost-env/bin/PhageBoost", line 8, in <module>
    sys.exit(main())
  File "/home/artic/.local/lib/python3.7/site-packages/PhageBoost/main.py", line 216, in main
    genecalls = call_genes(fasta, meta, min_size_of_contig)
  File "/home/artic/.local/lib/python3.7/site-packages/PhageBoost/main.py", line 29, in call_genes
    contig, meta)
  File "/home/artic/.local/lib/python3.7/site-packages/PhageBoost/get_genecalls.py", line 22, in get_genecalls_for_contig
    p = pyrodigal.Pyrodigal(meta=meta)
AttributeError: module 'pyrodigal' has no attribute 'Pyrodigal'

```

Version 0.7 of Pyrodigal removed `pyrodigal.Pyrodigal` from their build. Replacing this with `pyrodigal==0.6.4` fixes this issue.

**Comment by tsp-kucbd** [comment]
We changed the code to using the new pyrodigal syntax in the GitHub version and will later push into pip too.
For now you can install it with
`pip install git+https://github.com/ku-cbd/PhageBoost `

**Comment by GracaP88** [comment]
When using fasta files I get the error: AttributeError: module 'pyrodigal' has no attribute 'Pyrodigal'

When using a genebank file I get the error: after min_size_of_contig 10000, no contigs were left. This caused the run to fail

I already installed pip install git+https://github.com/ku-cbd/PhageBoost

Can you help me please?
