### ISSUE TITLE
Python error after installatin

### ISSUE THREAD

**Issue by shaman-narayanasamy** [ku-cbd/PhageBoost#31]
Dear authors/developers,

I am unable to execute PhageBoost after installation via conda + pip. Here are the command I issued:
```
$ conda env remove -n phageboost
$ conda create -y -n phageboost python=3.7
$ conda activate phageboost
$ pip install PhageBoost
(no obvious error/warnings)
$ PhageBoost -h
Traceback (most recent call last):
  File "/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/bin/PhageBoost", line 5, in <module>
    from PhageBoost.main import main
  File "/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/__init__.py", line 1, in <module>
    from PhageBoost import get_genecalls, get_predictions, get_matches, calc_features, main, bbcache
  File "/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/lib/python3.7/site-packages/PhageBoost/bbcache.py", line 6, in <module>
    from cachier import cachier
  File "/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/lib/python3.7/site-packages/cachier/__init__.py", line 1, in <module>
    from .core import (
  File "/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/lib/python3.7/site-packages/cachier/core.py", line 20, in <module>
    from typing import TYPE_CHECKING, Callable, Literal, Optional, TypedDict, Union
ImportError: cannot import name 'Literal' from 'typing' (/Users/shaman.narayanasamy/opt/miniconda3/envs/phageboost/lib/python3.7/typing.py)
```

I tested it on two independent systems, both resulting in the same error. I also skimmed though the current open and closed issues on the github but could not find anything related to this issue.  I would appreciate your help in solving this issue.

I look forward to hearing from you.

Best regards,
Shaman

**Comment by danzheng7372** [comment]
Hi, did you find the solution? I have the same problem.

**Comment by naturepoker** [comment]
Just writing to add I have the same issue as well - conda environment with python version 3.7, along with 

```
conda install xgboost=1.0.2
```

**Comment by shaman-narayanasamy** [comment]
> Hi, did you find the solution? I have the same problem.

Hi! No, I have not found a solution.

**Comment by gwickh** [comment]
I am also having this problem and have not found a solution.

**Comment by gwickh** [comment]
Based on this
```shell
File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py", line 5, in
from typing import Optional, TypedDict, Union
```
You should go into `/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py` and change

```python
from typing import Optional, TypedDict, Union
```
to
```python
from typing import Optional, Union
from typing_extensions import TypedDict
```
Let me know if it works!

**Comment by danzheng7372** [comment]
> Based on this
> 
> ```shell
> File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py", line 5, in
> from typing import Optional, TypedDict, Union
> ```
> 
> You should go into `/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py` and change
> 
> ```python
> from typing import Optional, TypedDict, Union
> ```
> 
> to
> 
> ```python
> from typing import Optional, Union
> from typing_extensions import TypedDict
> ```
> 
> Let me know if it works!

Hi, thank you for the prompt reply. I have tried again but seemed like more errors in config.py and typing.py. Here are the command I issued:
(PhageBoost-env) wet@brl:~$ PhageBoost -h
Traceback (most recent call last):
  File "/home/wet/miniconda3/envs/PhageBoost-env/bin/PhageBoost", line 5, in <module>
    from PhageBoost.main import main
  File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/PhageBoost/__init__.py", line 1, in <module>
    from PhageBoost import get_genecalls, get_predictions, get_matches, calc_features, main, bbcache
  File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/PhageBoost/bbcache.py", line 6, in <module>
    from cachier import cachier
  File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/__init__.py", line 2, in <module>
    from .config import (
  File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py", line 8, in <module>
    from ._types import Backend, HashFunc, Mongetter
  File "/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/_types.py", line 1, in <module>
    from typing import TYPE_CHECKING, Callable, Literal
ImportError: cannot import name 'Literal' from 'typing' (/home/wet/miniconda3/envs/PhageBoost-env/lib/python3.7/typing.py)

**Comment by gwickh** [comment]
Are you able to tell me which Python 3.7 release you are using? Python 3.7.12 doesn't seem to raise that error

**Comment by danzheng7372** [comment]
Hi, 
I have checked that I am using the Python 3.7.12 release. Thank you very much for the following.

<img width="609" alt="Screenshot 2024-03-15 at 18 02 04" src="https://github.com/ku-cbd/PhageBoost/assets/161743370/07969c1d-c018-4e09-93ad-d4291327743d">

**Comment by danzheng7372** [comment]
Hi, I solved this problem based on the solution provided by [gwickh]. Thank you very much for the help and guidance! 

So in my case, I revised two files. 
(1) miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py, change `from typing import Optional, Union, TypedDict` to `from typing import Optional, Union` and `from typing_extensions import TypedDict`
(2) miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/_types.py, change `from typing import TYPE_CHECKING, Callable, Literal` to `from typing import TYPE_CHECKING, Callable` and `from typing_extensions import Literal`

Hope this helps some people with the same errors.

**Comment by AndAvia** [comment]
@danzheng7372 Solved my problem `ImportError: cannot import name 'TypedDict' from 'typing' (/data4/machuang/miniconda3/envs/phageboost/lib/python3.7/typing.py)`  
Here is my installation process, in China you can use Tsinghua Source Acceleration 
 `conda create -y -n phageboost python=3.7 `
`conda activate phageboost`
#In China you can use accelerated with Tsinghua Mirror
`pip install typing_extensions PhageBoost --index-url https://pypi.tuna.tsinghua.edu.cn/simple`

#Modify the following files
(1) miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/config.py, change` from typing import Optional, Union, TypedDict` to `from typing import Optional, Union` and `from typing_extensions import TypedDict`
(2) miniconda3/envs/PhageBoost-env/lib/python3.7/site-packages/cachier/_types.py, change` from typing import TYPE_CHECKING, Callable, Literal` to `from typing import TYPE_CHECKING, Callable` and `from typing_extensions import Literal`

#At last
`PhageBoost -h`

**Comment by danzheng7372** [comment]
Good to konw that it works! @AndAvia

**Comment by tsp-kucbd** [comment]
We have updated the current PhageBoost version to use XGBoost 2 and recent Python(3.11), BioPython and Pyrodigal.  As PhageBoost v2.0 is under development, only the git hub version of PhageBoost v1 will be corrected.
Please give it a try.

**Comment by aryehjc** [comment]
hello, I followed all steps above and receive the error line 47, in CacheEntry
    value: Any
NameError: name 'Any' is not defined.
Please help thank you!
