### ISSUE TITLE
example runnin failed

### ISSUE THREAD

**Issue by igortru** [ku-cbd/PhageBoost#32]
PhageBoost -f example/data/NC_000907.fasta.gz -o results
processing: NC_000907
time after genecalls: 2.24992036819458
time after feature calculations: 8.712299346923828
[22:44:13] WARNING: ../src/learner.cc:1040: 
  If you are loading a serialized model (like pickle in Python, RDS in R) generated by
  older XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for more details about differences between saving model and serializing.

[22:44:13] WARNING: ../src/learner.cc:749: Found JSON model saved before XGBoost 1.6, please save the model using current version again. The support for old JSON model will be discontinued in XGBoost 2.3.
[22:44:13] WARNING: ../src/tree/./updater_quantile_hist.h:248: Attempted to load internal configuration for a model file that was generated by a previous version of XGBoost. A likely cause for this warning is that the model was saved with saveRDS() in R or pickle.dump() in Python. We strongly ADVISE AGAINST using saveRDS() or pickle.dump() so that the model remains accessible in current and upcoming XGBoost releases. Please use xgb.save() instead to preserve models for the long term. For more details and explanation, see https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html
[22:44:13] WARNING: ../src/learner.cc:438: 
  If you are loading a serialized model (like pickle in Python, RDS in R) generated by
  older XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for more details about differences between saving model and serializing.

Traceback (most recent call last):
  File "/home/tolstoy/.local/bin/PhageBoost", line 8, in <module>
    sys.exit(main())
  File "/home/tolstoy/.local/lib/python3.7/site-packages/PhageBoost/main.py", line 223, in main
    model, feats, feats_, limit = read_model_from_file(model_file)
  File "/home/tolstoy/.local/lib/python3.7/site-packages/PhageBoost/main.py", line 65, in read_model_from_file
    feats_ = [i.replace('-delta', '') for i in feats]
TypeError: 'NoneType' object is not iterable

**Comment by wangdi2016** [comment]
I had the same issue. I figured it out after downgrading xgboost from 2.1.1 to 1.1.1. I can run the test case successfully.

== here is the output ==
processing: NC_000907
time after genecalls: 2.1909637451171875
time after feature calculations: 10.072350263595581
time after predictions: 11.75052547454834
{'phage6': 51, 'phage5': 26}

Here is my requirments.txt
--------------------------------------
biopython==1.76
joblib
more-itertools
numpy
pandas
pickleshare
pyrodigal==0.6.4
scipy
tables
xgboost==1.1.1
cachier
---------------------------------------

**Comment by tsp-kucbd** [comment]
We have updated the current PhageBoost version to use XGBoost 2 and recent Python(3.11), BioPython and Pyrodigal.  As PhageBoost v2.0 is under development, only the git hub version of PhageBoost v1 will be corrected.
Please give it a try.
